### ISSUE TITLE
404 page after login

### ISSUE THREAD

**Issue by w3slley** [itsjustaplant/Lyrics-for-spotify---Spofly#2]
After the login, the user is redirected to a Not Found page.
![image](https://user-images.githubusercontent.com/24323626/112467710-4d1ba900-8d5f-11eb-8593-020b919c25d3.png)

Maybe a page which highlights "Now go on Spotify and play a song" would be more intuitive. A Not Found page looks like some error have occurred or that the user is doing something wrong. 

Good job on the web app. It's really awesome!

**Comment by itsjustaplant** [comment]
First of all thank you for compliment that just made my day. In a day or two, i'll start editing the page to make it more user friendly.
Stay with music.
